#!/bin/sh

  concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "build:es,build:cjs" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "npm run build:es" \
    "npm run build:cjs"